### ISSUE TITLE
Navigation bar missing after scrolling

### ISSUE THREAD

**Issue by arryanggaputra** [godness84/react-native-recyclerview-list#12]
I'm using `react-native-navigation` by wix, they have option to hide navbar when scrolling, the problem is when i try to scrolling a bit fast to bottom, navigation bar is hide like what i want, but when i scrolling to top navigation bar can not appear.

```javascript
  render() {
    var dataSource = new DataSource(
      this.props.activities,
      (item, index) => item.id
    );
    return (
      <View style={{ flex: 1 }}>
        <RecyclerviewList
          ListHeaderComponent={this._renderHeader}
          style={{ flex: 1 }}
          dataSource={dataSource}
          renderItem={this.renderActivities}
        />
      </View>
    );
  }
```

**Comment by godness84** [comment]
I've never used `react-native-navigation` so I don't know which could be the problem.

Does using a `FlatList` instead of `RecyclerviewList` solve the issue?
If you publish an example project on github or somewhere, in free time I'll give it a look.

**Comment by arryanggaputra** [comment]
@godness84 using flatlist is good, navigation bar hide on scroll is work as expected. The reason i use this library is about performance, this really help me. By the way, is there any option like `onReachEnd`? So , i can pull data on it.

**Comment by godness84** [comment]
There is a `onVisibleItemsChange` event that gives you the currently first and last visible item indexes. Since you know how many items the datasource contains, you can understand when you are approaching the end.

**Comment by godness84** [comment]
Closing this issue since there hasn't been any activity on it
