### ISSUE TITLE
Warning about missing keyExtractor 

### ISSUE THREAD

**Issue by arryanggaputra** [godness84/react-native-recyclerview-list#13]
When i enabled debugging, I always got warning about `DataSource.js:8 RecyclerViewList/DataSource: missing keyExtractor, it's strongly recommended to specify a keyExtractor function in order to use all the features correctly`

This is the code to define `dataSource` 
```javascript
    var dataSource = new DataSource(
      this.props.activities,
      (item, index) => item.id
    );
```

**Comment by Louies89** [comment]
@arryanggaputra  got any solution?
@godness84  Please help...

**Comment by maxme** [comment]
This is probably due to the defaultProps in `RecyclerViewList`. 

https://github.com/godness84/react-native-recyclerview-list/blob/54b731d32cf5e9a8aeab301b1fd55203051246b2/src/RecyclerViewList.js#L67-L72

**Comment by Louies89** [comment]
I found it.. 
As the warning is present in the constructor part of DataSource.js, whenever the "DataSource" is imported, that time no "keyExtractor" is provided, so the warning appears.

So the constructor method can be changed to overcome this.

@godness84  Please take a look into this issue.

**Comment by godness84** [comment]
you were right @maxme, solved!
