### ISSUE TITLE
scrollToIndex view position not consistent

### ISSUE THREAD

**Issue by ariona** [godness84/react-native-recyclerview-list#2]
Hi, thank you for building this package, It is really helpful.. especially for navigating between list items without providing the item height like FlatList and set initial item index when first viewing the list.

What bothering me now is the item position when the `scrollToIndex` is called. Sometime the target item is positioned at top, middle or even at the bottom container.

It only happen after calling the `scrollToIndex` method.

How can i fix this issue, if i remember it well on RN scrollview we can specify where we want the view positioned (top/middle/bottom by using 0.0-1.0 unit).

**Comment by godness84** [comment]
I'm working on it, soon an update

**Comment by godness84** [comment]
Try with new version: `0.2.1`.

Some improvements:
- `scrollToIndex` method accepts 2 new parameters: 
`viewPosition`: 0.0 - 1.0, where 0 is at the top, 1 at the bottom and 0.5 in the middle
`viewOffset`: is a fixed number of pixels to offset the final target position
- new prop `initialScrollOffset` to adjust the initial position of the scroll.
- better rendering performace

Anyway, read the README.md file for better explanation.

**Comment by ariona** [comment]
Thanks for the update, but i think it still doesn't work. Checkout my app demo here [scrollToIndex Demo](https://lh3.googleusercontent.com/3CIAXYPI8ters4jH7YkLNIrUAecbu7LSRBAawCuJ0SaU1D4h6p14HlKtNnp3sAKEUjH8fAxZVqHNZSjrzQe1uHhiizq-laGYSq67RaYomX3OJmbA1T5wAX5TjKVTSnvxkMyUwgAEo_M=w412-h732-no) (*It is a production build mode*)

- go to item 30 => the position is middle
- go to item 56 => the position is above the window (partially visible)
- go to item 182 => middle

Here is my code for navigating between item. I have set the `viewPosition` to 0
```js
this._scrollView.scrollToIndex({
    index : this.state.goToAyah - 1,
    animated : false,
    viewPosition : 0
})
```
*note that -1 is used for index based numbering*

**Comment by godness84** [comment]
You're right, `viewPosition` is not respected when `animated` is set to `false` and the view is not yet ready on the native side.

It should be fixed in version `0.2.2`.
Let me know.

**Comment by ariona** [comment]
@godness84 You are awesome mate 😄  it's working perfectly now.

I've been suffering from navigating the items in Flalist with variable items.

Any plan for adding support for IOS?

God bless you 👍

**Comment by godness84** [comment]
Thank you @ariona!
At the moment there is no plan for adding support for iOS, mostly because I don't know ObjectiveC/Swift :)
