### ISSUE TITLE
Zero Copy rendering support.

### ISSUE THREAD

**Issue by Louies89** [godness84/react-native-recyclerview-list#21]
@godness84 
Hi,
I am using realm for my app. realm has zero copy mechanism, so it provides a object which shall point to the data present in the memory. And data at any time can be retrieved using the object (similar to json object array.)

Can you please provide some insight, how it can be implemented ?

**Comment by godness84** [comment]
I think that you can directly pass your realm results to the constructor of `DataSource` and then listen to the changes from realm and notify the `DataSource`.

Something like this:

```
const results = realm.objects('Person');
const dataSource = new DataSource(results, (item, index) => item.id);

results.addListener((collection, changes) => {
  dataSource.setDirty();
});
```

I didn't try this code so take it as is.
Maybe you will have troubles when adding/removing items from `realm.objects('Person')`. In this case, listen better to the changes in realm and in case of addition or removal, instantiate a new `DataSource`.

**Comment by Louies89** [comment]
Hi @godness84 
I tried
 ```
const results = realm.objects('Person');
const dataSource = new DataSource(results, (item, index) => item.id);
```


but has not used the listener till yet... but the above 2 lines are working. And used below code to render the list items.

```
 render() {
    return (
      <RecyclerviewList
        style={{flex: 1}}
        dataSource={dataSource}
        initialListSize = {10}
        windowSize = {100}
        renderItem={({item, index}) => (
          <View style={styles.container}>
            <Text>{item.name} - {index}</Text>
          </View>
        )} 
      />
    )
  }
```

I have given windowSize = {100}, so 1st time when i scroll down it goes smoothly up to 110 rows, after that it shows blank space, and takes around 2/3 seconds to render the rows after 110. Similarly if I am coming up from 110 to upward, rows before 10 are not getting rendered, for this if I am doing little up-down scrolling, the rows are getting rendered.

May be I am missing some configuration or something else can be done. And can we achieve whatsapp like faster rendering? (WhatsApp does very fast rendering even though the chat list contains more 300 rows)

Please can you give some suggestion for this?

**Comment by godness84** [comment]
turn off DEV mode, performance should improve.

otherwise, publish on github a project that I can look at and help you.

2018-04-10 17:40 GMT+02:00 Louies89 <notifications@github.com>:

**Comment by Louies89** [comment]
@godness84  I do not have a proper project. but below are my apps requirements:
The app shall have a db of contacts. which is implemented using realm db. The db schema is :

```
const CntctSchema = {
    name: 'Contacts',
    primaryKey: 'id',
    properties: {
      uid		: {type: 'int'},
      mob		: {type: 'string'},
      name		: {type: 'string'},
      altcntct	: {type: 'string?'},
      bday		: {type: 'date?'},
      others    : {type: 'date?'},
    }
};
```

The contacts are get sync with phone book of the mobile. The app should show list of contacts with their name and when user selects any of the contact, it will show all the details of the contact. for trial purpose  I used below code while storing 350 contacts in the realm db :

```
import React, { Component } from "react";
import { View, Text, Dimensions } from "react-native";

import RecyclerviewList, { DataSource } from 'react-native-recyclerview-list';

import Cntact from './src/realm/RmCntcts'   
let CntactRead = Cntact.objects('Contacts');  <=====This is the object pointing to Realm contacts schema


var data;

if(CntactRead && CntactRead.length){
  data = Array.from(CntactRead);
}
else{
  data = [{uid:0,name:'Nothing to Show'}];
}

export default class RecycleList extends React.Component {
  constructor(args) {
    super(args);
    this.state = { 
      dataSource: new DataSource(data, (item,index) => item.uid);
    }
  }


  render() {
    return (
      <RecyclerviewList
        style={{flex: 1}}
        dataSource={this.state.dataSource}
        initialListSize = {10}
        windowSize = {100}
        renderItem={({item, index}) => (
          <View style={styles.container}>
            <Text>{item.name} - {index}</Text>
          </View>
        )} 
      />
    )
  }
}


const styles = {
  container: {
    justifyContent: "space-around",
    alignItems: "center",
    flex: 1,
    backgroundColor: "white",
    borderWidth:1,
    borderColor:'gray',
    height:80
  },
};
```

So if you will see below pictures, moving to 261 row happened smoothly but after that no rows rendered, after 2/3 seconds(sometimes takes 5/6 seconds also), rows rendered
![image](https://user-images.githubusercontent.com/30086899/38583967-6a5a4a42-3d32-11e8-8f0e-ee33b8522602.png)

![image](https://user-images.githubusercontent.com/30086899/38583974-70b5bc0a-3d32-11e8-8297-885d97e6b2a3.png)

Even after in DEV mode off, also same problem exists..
So this is the lagging problem I am facing... please let me know anything can be done to enhance this...

Thank You :)

**Comment by godness84** [comment]
I'm using this lib with no special performance loss. It means that probably your project contains some misconfiguration or the integration with realm doesn't work. Maybe the problem resides in the version of react, realm or this lib. There are too many details that can cause your problem.

That's why I asked you to publish a repo that I can work with. Do it please, and then I can help you.

**Comment by Louies89** [comment]
Hi @godness84 ,
I have created a project at https://github.com/Louies89/TrialRealm...
The android and ios folder I am unable to load... Please look in to the App.js file and RealmCntcts.js and you can do npm init to create the RN project...

Pleaese let me know if anything extra you want...

**Comment by godness84** [comment]
Tried your project and it scrolls smoothly. I tried it on a real device, with DEV mode on/off and the performances are ok, even after the 261th row.

**Comment by Louies89** [comment]
@godness84 
Its working fine now, there is no lagging..., when i did DEV mode off, its very first, even 400 lists also working very fine..

Thank you a lot for your time... :)

**Comment by Louies89** [comment]
@godness84 it is lagging as the profile images and other information has to be shown in each row of the list :(
