### ISSUE TITLE
Why are the stars too little?

### ISSUE THREAD

**Issue by qq326646683** [godness84/react-native-recyclerview-list#23]
I test native Android by RecyclerView and your library on RN. the data count are all 1000. But it shows slowly by using your library.
http://7xt3sl.com2.z0.glb.qiniucdn.com/2018-06-12_16_58_22.mp4

**Comment by vampirekiss** [comment]
40-60fps on my redmi 5s plus

**Comment by godness84** [comment]
@qq326646683 as stated [here](https://facebook.github.io/react-native/docs/performance#profiling)

> But first, make sure that Development Mode is OFF! You should see __DEV__ === false, development-level warning are OFF, performance optimizations are ON in your application logs.

And as stated [here](https://facebook.github.io/react-native/docs/performance#running-in-development-mode-dev-true)

> make sure to test performance in [release builds](https://facebook.github.io/react-native/docs/signed-apk-android#testing-the-release-build-of-your-app).

**Comment by qq326646683** [comment]
yes,you are right, I will try it tomorrow by release apk. 
by the way,can you add pull to refresh and loadmore in the future?

**Comment by qq326646683** [comment]
it is smooth on release apk, thx very much
