### ISSUE TITLE
state change not updating ui

### ISSUE THREAD

**Issue by kenkotch** [godness84/react-native-recyclerview-list#24]
I am updating my state in the dataSource but the UI is not re-rendering. 
Have tried setting in render: `let dataSource = new DataSource(this.state.eventsList, (item, index) => item.id)` 
and setting a state obj called dataSource. After I populate this.state.eventsList, I: `this.setState({ dataSource: new DataSource(this.state.eventsList, (item, index) => item.id) })`

Both render initial scene correctly but when I update `this.state.eventsList` I cannot get a re-render.

thought I could use setDirty but dont know where to put it/ how to implement. Help!

**Comment by patrickkempff** [comment]
I think you should call this.state.dataSource.setDirty()

**Comment by kenkotch** [comment]
Thanks patrick. setDirty didnt work either. I solved it using .get() and .set() instead of this.setState to update state
