### ISSUE TITLE
react-native 0.56 Failed to execute aapt

### ISSUE THREAD

**Issue by kenkotch** [godness84/react-native-recyclerview-list#27]
I am working on updating my RN Android app to RN0.56
When I build a release version with recyclerview list I get the following error: 

>Execution failed for task ':react-native-recyclerview-list:verifyReleaseResources'.
>  `>` com.android.ide.common.process.ProcessException: Failed to execute aapt

Any ideas on how to get past?

**Comment by tje3d** [comment]
This is not related to recyclerview, set `android.enableAapt2=false` inside `gradle.properties` and you are set!

**Comment by kenkotch** [comment]
Thanks. That works as a workaround until RN fixes the issue `android.enableAapt2=false` is deprecated
