### ISSUE TITLE
Use new React PropTypes import

### ISSUE THREAD

**Issue by fgeorgsson** [godness84/react-native-recyclerview-list#3]
React recently moved PropTypes to a separate module.

This code:
```
import React, { Component, PropTypes } from 'react';
```

Needs to be:
```
import PropTypes from 'prop-types';
import React, { Component } from 'react';
```

Any chance of a new version on NPM? I think the change is needed from React Native 0.45.

**Comment by godness84** [comment]
I think before the end of this week. Anyway if you want to submit a PR you're welcome :)

**Comment by fgeorgsson** [comment]
I might but I think one needs to update the docs to reflect that version x requires react native version y etc as well. I am in no rush. :)

**Comment by godness84** [comment]
This change is needed from RN 0.49.0, before there was just a warning telling that in future it will not work.

**Comment by godness84** [comment]
PropTypes correctly imported and updated README
