### ISSUE TITLE
Cannot build project with RN 0.48.0

### ISSUE THREAD

**Issue by nim23** [godness84/react-native-recyclerview-list#6]
![screen shot 2017-10-13 at 11 31 46](https://user-images.githubusercontent.com/1999331/31542515-43648732-b00a-11e7-84fe-8490e607c940.png)

I keep getting this error when trying to build the project with `react-native-recyclerview-list`. 

React native version is 0.48.0, also tried 0.49.0.

**Comment by godness84** [comment]
Can you check that you truely installed RN 0.48.0 or 0.49.0?
Because the `VelocityHelper` class was introduced in RN 0.47.0 so it's a weird error.

**Comment by nim23** [comment]
You can close this issue, this was mostly because one of the RN packages in the project was importing RN 0.20.0 in it's gradle dependencies, updating the package fixed the issue. Plus just want to say thanks for the package, seeing great results with it atm, haven't tested it on a tablet yet where I have had most pain on orientation change with flatlist. Hopefully it holds out.

**Comment by godness84** [comment]
Let me know if you will perceive any improvements using this lib instead of
FlatList!

Il ven 13 ott 2017 20:52 nim23 <notifications@github.com> ha scritto:
