### ISSUE TITLE
Grid support

### ISSUE THREAD

**Issue by nim23** [godness84/react-native-recyclerview-list#7]
Is there a reason there is no support for grid layout? How hard would it be to start supporting grid layout? Asking to see if I can contribute towards adding support for grid layout.

**Comment by godness84** [comment]
If you need a simple grid, where every item of a row as the same height then it's already supported. Let's suppose you want a grid made of 3 columns: you just need to render 1/3 of your items and in 'renderItem' you need to render a View with 'flexDirection' as 'row' that contains 3 of your items with the same width. 

If you mean a staggered grid, where items have different heights and the bottom of an item is near the top of another item, then you need to change the native code of this lib using a 'StaggeredGridLayoutManager' as 'LayoutManager' of the RecyclerView. Consider that 'scrollToIndex' method supposes that there's a 'LinearLayoutManager' so you should update that part accordingly.

**Comment by nim23** [comment]
Thanks. I am after the first scenario you mentioned and it works for me. I am seeing a slight delay when re-rendering views on orientation change, but that could be totally something on my side.

**Comment by ashokkumar88** [comment]
@nim23 can u please share how you achieve masonry layout?
