### ISSUE TITLE
Blank rows

### ISSUE THREAD

**Issue by zenchanhk** [godness84/react-native-recyclerview-list#9]
Hi,
I still saw the blank rows when scrolling a bit fast, is there a way to solve this? Thanks.

**Comment by godness84** [comment]
Try to tweak the `windowSize` prop, maybe increasing it.
Anyway, consider that performances are quite different when you build your app for release (not just release mode of the JS, but compiling the whole android app for release).

**Comment by zenchanhk** [comment]
I‘ve tried to adjust `windowSize` to 80, it seems to become a bit better. Thanks.
